### ISSUE TITLE
Favicon's not working 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#220]
It looks like every site we have has the same favicon they are all b1.church

https://southsideonline.com/. is an example where I uploaded their favicon but it does not change.

**Comment by jzongker** [comment]
This is fixed now

**Comment by mbyrdLCS** [comment]
This issue is back all favicons are churchapps not the church logo
