### ISSUE TITLE
Lessons.church not displaying edited lessons correctly on b1 app

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#296]
YOu can edit which parts you want teachers to see on the lesssons.church website this works but is not being displayed correctly on the b1 app. 

<img width="1441" alt="Screenshot 2024-05-31 at 8 43 24 PM" src="https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/74a90da1-0065-4f8b-850f-89c65e04ddba">
![IMG_1881](https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/18e533e1-f495-44de-804e-a08e457b7e22)

**Comment by mbyrdLCS** [comment]
![IMG_1881](https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/9f55ce3a-9623-4a46-92b1-b30a45b0289b)

**Comment by jzongker** [comment]
B1 just iFrames in content from lessons.church here.  The problem is in LessonsApp at this url:

https://lessons.church/b1/venue/[venueId]?classroomId=[classroomId]

Schedule a lesson in a classroom, then edit it to remove some sections.  Click the subscribe button to get the link to this page to reproduce the issue.

**Comment by Himali-Malvawala** [comment]
Fixed.

**Comment by mbyrdLCS** [comment]
This Problem came back. The lessons parts that you mark out are still showing up

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS Is this still an issue?

**Comment by mbyrdLCS** [comment]
No this looks like it is working correctly now. Thanks!!
